import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BackgroundImage from "@/component/BackgroundImage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div
          style={{
            position: "fixed",
            width: "100%",
            height: "100vh",
            zIndex: 0,
          }}
        >
          <BackgroundImage src="/Main.webp" growthRate={0.2} transitionDuration={0.3} />
        </div>

        <main className="relative">{children}</main>
      </body>
    </html>
  );
}
